### ISSUE TITLE
Design schematic PDF generation CI job

### ISSUE THREAD

**Issue by jaylamb** [apcountryman/prototype-kicad-project-ci-cd#13]
**Feature Design**
- [ ] Add schematic PDF generation CI script (`ci/generate-schematic-pdf`) which will create a directory (`schematic-pdfs`) within the project repository. The directory should be the target for the [KiAuto eeschema_do script's export function](https://github.com/INTI-CMNB/KiAuto#export-a-schematic-to-pdf-or-svg), which should generate PDFs for any schematic sheets belonging to the project.
- [ ] Each PDF should be generated as a [GitHub artifact](https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts) with a retention period of seven days.

**Feature Use Case**

This CI job will run automatically as a part of pull requests, releases, etc... and will ensure that PDF versions of all schematic sheets are available for use by users/reviewers.

**Detailed Design**

- [ ] Add `ci/generate-schematic-pdf` to project:
  - [ ] Supported options:
      - [ ] `--help`: See other project scripts
      - [ ] `--version`: See other project scripts
    - [ ] `function error()`: See other project scripts
    - [ ] `function abort()`: See other project scripts
    - [ ] `function display_help_text()`: See other project scripts
    - [ ] `function display_version()`: See other project scripts
    - [ ] `function main()`: See other project scripts
    - [ ] `function generate_schematic_pdf()`:
```bash
local schematics; mapfile -t schematics < <( git -C "$repository" ls-files '*.sch' ':!:*-sheet-*.sch' | xargs -r -d '\n' -I '{}' find "$repository/{}" ); readonly schematics

for schematic in "${schematics[@]}"; do
    if ! "$repository/utilities/KiAuto/src/eeschema_do" export -a "$schematic" "$repository/schematic-pdfs"; then
        abort
    fi
done
```

- [ ] Add schematic PDF exporting and PDF artifact generation to `.github/workflows/ci.yml`:
```yaml
generate-schematic-pdf:
    name: Generate schematic PDF(s)
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
          with:
              submodules: recursive
        - name: Generate schematic PDF(s)
          shell: bash
          run: ./ci/generate-schematic-pdf
        - name: Archive production artifacts
          uses: actions/upload-artifact@v2
          with:
            name: upload-schematics
            path: |
              schematic-pdfs
            retention-days: 7
```
