### ISSUE TITLE
Add schematic PDF(s) generation CI job

### ISSUE THREAD

**Issue by apcountryman** [apcountryman/prototype-kicad-project-ci-cd#15]
Add schematic PDF(s) generation CI job. The proposed design was outlined in #13.
- [ ] Add schematic PDF(s) generation CI script (`ci/generate-schematic-pdfs`)
    - [ ] Supported options:
        - [ ] `--help`: See other project scripts
        - [ ] `--version`: See other project scripts
    - [ ] `function error()`: See other project scripts
    - [ ] `function abort()`: See other project scripts
    - [ ] `function display_help_text()`: See other project scripts
    - [ ] `function display_version()`: See other project scripts
    - [ ] `function main()`: See other project scripts
    - [ ] `function generate_schematic_pdfs()`:
```bash
local schematics; mapfile -t schematics < <( git -C "$repository" ls-files '*.sch' ':!:*-sheet-*.sch' | xargs -r -d '\n' -I '{}' find "$repository/{}" ); readonly schematics

for schematic in "${schematics[@]}"; do
    if ! "$repository/utilities/KiAuto/src/eeschema_do" export -a "$schematic" "$repository/schematic-pdfs"; then
        abort
    fi
done
```
- [ ] Add schematic PDF(s) generation (and archiving) CI job to `.github/workflows/ci.yml`:
```yaml
generate-schematic-pdfs:
    name: Generate schematic PDF(s)
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
          with:
              submodules: recursive
        - name: Generate schematic PDF(s)
          shell: bash
          run: ./ci/generate-schematic-pdfs
        - name: Archive generated schematic PDF(s)
          uses: actions/upload-artifact@v2
          with:
            name: schematic-pdfs
            path: schematic-pdfs
            retention-days: 7
```
