### ISSUE TITLE
Design traditional BOM generation CI job

### ISSUE THREAD

**Issue by jaylamb** [apcountryman/prototype-kicad-project-ci-cd#19]
**Feature Design**
Add traditional (spreadsheet style) bill of materials (BOM) generation CI script (`ci/generate-traditional-bom`) which will create a directory (`bom`) within the project repository, if it does not already exist. The directory should be the target for the [KiBom KiBOM_CLI script's](https://github.com/SchrodingersGat/KiBoM) output. This output should be a basic HTML BOM, which can be modified using a configuration file, `bom.ini`, which is automatically generated the first time the script is run.

_Note: The script requires the BOM be available in the XML format. The [KiAuto eeschema_do script's `bom_xml` function](https://github.com/INTI-CMNB/KiAuto#update-bom-xml-or-basic-bom-generation) should be used to produce this._

**Feature Use Case**
This CI job will run automatically as a part of pull requests, releases, etc... and will produce a simple bill of materials for all printed circuit boards contained within a project repository.

**Detailed Design**
- [ ] Add [KiBOM](https://github.com/SchrodingersGat/KiBoM) as a submodule to this project:
```bash
git submodule add git@github.com:SchrodingersGat/KiBoM.git utilities/KiBOM
```
- [ ] Add `ci/generate-traditional-bom` to project:
  - [ ] Supported options:
      - [ ] `--help`: See other project scripts
      - [ ] `--version`: See other project scripts
    - [ ] `function error()`: See other project scripts
    - [ ] `function abort()`: See other project scripts
    - [ ] `function display_help_text()`: See other project scripts
    - [ ] `function display_version()`: See other project scripts
    - [ ] `function main()`: See other project scripts
    - [ ] `function generate_traditional_bom()`:

```bash
local schematics; mapfile -t schematics < <( git -C "$repository" ls-files '*.sch' ':!:*-sheet-*.sch' | xargs -r -d '\n' -I '{}' find "$repository/{}" ); readonly schematics

for schematic in "${schematics[@]}"; do
    if ! "$repository/utilities/KiAuto/src/eeschema_do" bom_xml "$schematic" "$repository"; then
        abort
    fi  
done

local netlists; mapfile -t netlists < <( find *.xml ); readonly netlists

    for netlist in "${netlists[@]}"; do
        local bom_name=$( basename "$netlist" .xml )
        if ! python3 "$repository/utilities/KiBOM/KiBOM_CLI.py" -d bom "$netlist" "$bom_name.html"; then
            abort
        fi  
done
```

- [ ] Add traditional bill of materials generation to `.github/workflows/ci.yml`:
```yaml
generate-traditional-bom:
    name: Generate traditional BOM
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
          with:
              submodules: recursive
        - name: Generate traditional BOM
          shell: bash
          run: ./ci/generate-traditional-bom
```
