### ISSUE TITLE
Add traditional BOM(s) generation CI job

### ISSUE THREAD

**Issue by apcountryman** [apcountryman/prototype-kicad-project-ci-cd#20]
Add traditional BOM(s) generation CI job. The proposed design was outlined in #19.
- [ ] Add [KiBom](https://github.com/SchrodingersGat/KiBoM) as a repository submodule
```bash
git submodule add ../KiBoM utilities/KiBoM
```

- [ ] Add traditional BOM(s) generation CI script (`ci/generate-traditional-boms`)
    - [ ] Supported options:
        - [ ] `--help`: See other project scripts
        - [ ] `--version`: See other project scripts
    - [ ] `function error()`: See other project scripts
    - [ ] `function abort()`: See other project scripts
    - [ ] `function display_help_text()`: See other project scripts
    - [ ] `function display_version()`: See other project scripts
    - [ ] `function main()`: See other project scripts
    - [ ] `function generate_traditional_boms()`:
```bash
local schematics; mapfile -t schematics < <( git -C "$repository" ls-files '*.sch' ':!:*-sheet-*.sch' | xargs -r -d '\n' -I '{}' find "$repository/{}" ); readonly schematics

for schematic in "${schematics[@]}"; do
    if ! "$repository/utilities/KiAuto/src/eeschema_do" bom_xml "$schematic" "$repository/temp"; then
        abort
    fi
done

local boms_xml; mapfile -t boms_xml < <( find "$repository" -name '*.xml' ); readonly boms_xml

for bom_xml in "${boms_xml[@]}"; do
    local bom=$( basename "$bom_xml" .xml )

    if ! "$repository/utilities/KiBoM/KiBOM_CLI.py" "$bom_xml" -d "$repository/traditional-boms" "$repository/traditional-boms/$bom.csv"; then
        abort
    fi

    if ! "$repository/utilities/KiBoM/KiBOM_CLI.py" "$bom_xml" -d "$repository/traditional-boms" "$repository/traditional-boms/$bom.html"; then
        abort
    fi

    if ! "$repository/utilities/KiBoM/KiBOM_CLI.py" "$bom_xml" -d "$repository/traditional-boms" "$repository/traditional-boms/$bom.xml"; then
        abort
    fi

    if ! "$repository/utilities/KiBoM/KiBOM_CLI.py" "$bom_xml" -d "$repository/traditional-boms" "$repository/traditional-boms/$bom.xslx"; then
        abort
    fi
done
```

- [ ] Add traditional BOM(s) generation (and archiving) CI job to `.github/workflows/ci.yml`:
```yaml
generate-traditional-boms:
    name: Generate traditional BOM(s)
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
            with:
                submodules: recursive
        - name: Generate traditional BOM(s)
            shell: bash
            run: ./ci/generate-traditional-boms
        - name: Archive generated traditional BOM(s)
            uses: actions/upload-artifact@v2
            with:
                name: traditional-boms
                path: traditional-boms
                retention-days: 7
```
