### ISSUE TITLE
Design interactive BOM(s) generation CI job

### ISSUE THREAD

**Issue by jaylamb** [apcountryman/prototype-kicad-project-ci-cd#22]
**Feature Design**
Add interactive HTML bill of materials (BOM) generation CI script (`ci/generate-interactive-boms`) which will create a directory (`bom`) within the project repository, if it does not already exist. The directory should be the target for the [InteractiveHtmlBom generate_interactive_bom script's](https://github.com/openscopeproject/InteractiveHtmlBom/wiki/Usage#standalone-script) output.

**Feature Use Case**
This CI job will run automatically as a part of pull requests, releases, etc... and will produce a bill of materials for all printed circuit boards contained within a project repository.

**Detailed Design**
- [ ] Add [InteractiveHtmlBom](https://github.com/openscopeproject/InteractiveHtmlBom) as a submodule to this project:
```bash
git submodule add ../InteractiveHtmlBom utilities/InteractiveHtmlBom
```
- [ ] Add `ci/generate-interactive-boms` to project:
  - [ ] Supported options:
      - [ ] `--help`: See other project scripts
      - [ ] `--version`: See other project scripts
   - [ ] `function error()`: See other project scripts
   - [ ] `function abort()`: See other project scripts
   - [ ] `function display_help_text()`: See other project scripts
   - [ ] `function display_version()`: See other project scripts
   - [ ] `function main()`: See other project scripts
   - [ ] `function generate_interactive_boms()`:

```bash
local layouts; mapfile -t layouts < <( git -C "$repository" ls-files '*.kicad_pcb' | xargs -r -d '\n' -I '{}' find "$repository/{}" ); readonly layouts

for layout in "${layouts[@]}"; do
    if ! "$repository/utilities/InteractiveHtmlBom/InteractiveHtmlBom/generate_interactive_bom.py" "$layout"; then
        abort
    fi  
done
```

- [ ] Add interactive BOM(s) generation (and archiving) CI job to `.github/workflows/ci.yml`:
```yaml
generate-interactive-boms:
    name: Generate interactive BOM(s)
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
            with:
                submodules: recursive
        - name: Generate interactive BOM(s)
            shell: bash
            run: ./ci/generate-interactive-boms
        - name: Archive generated interactive BOM(s)
            uses: actions/upload-artifact@v2
            with:
                name: interactive-boms
                path: interactive-boms
                retention-days: 7
```
