### ISSUE TITLE
Add interactive BOM(s) generation CI job

### ISSUE THREAD

**Issue by apcountryman** [apcountryman/prototype-kicad-project-ci-cd#23]
Add interactive BOM(s) generation CI job. The proposed design was outlined in #22.
- [ ] Add [InteractiveHtmlBom](https://github.com/openscopeproject/InteractiveHtmlBom) as a repository submodule:
```bash
git submodule add ../InteractiveHtmlBom utilities/InteractiveHtmlBom
```
- [ ] Add interactive BOM(s) generation CI script (`ci/generate-interactive-boms`):
    - [ ] Supported options:
        - [ ] `--help`: See other project scripts
        - [ ] `--version`: See other project scripts
    - [ ] `function error()`: See other project scripts
    - [ ] `function abort()`: See other project scripts
    - [ ] `function display_help_text()`: See other project scripts
    - [ ] `function display_version()`: See other project scripts
    - [ ] `function main()`: See other project scripts
    - [ ] `function generate_interactive_boms()`:
```bash
local layouts; mapfile -t layouts < <( git -C "$repository" ls-files '*.kicad_pcb' | xargs -r -d '\n' -I '{}' find "$repository/{}" ); readonly layouts

for layout in "${layouts[@]}"; do
    if ! "$repository/utilities/InteractiveHtmlBom/InteractiveHtmlBom/generate_interactive_bom.py" --dest-dir "$repository/interactive-boms" "$layout"; then
        abort
    fi
done
```
- [ ] Add interactive BOM(s) generation (and archiving) CI job to `.github/workflows/ci.yml`:
```yaml
generate-interactive-boms:
    name: Generate interactive BOM(s)
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
            with:
                submodules: recursive
        - name: Generate interactive BOM(s)
            shell: bash
            run: ./ci/generate-interactive-boms
        - name: Archive generated interactive BOM(s)
            uses: actions/upload-artifact@v2
            with:
                name: interactive-boms
                path: interactive-boms
                retention-days: 7
```
