### ISSUE TITLE
Design PCB renders CI job

### ISSUE THREAD

**Issue by jaylamb** [apcountryman/prototype-kicad-project-ci-cd#33]
**Feature Design**
Add PCB renders generation CI script (`ci/generate-pcb-renders`) which will create a directory (`prodcution_files`) within the project repository, if it does not already exist. The directory should be the target for the [PcbDraw script's](https://github.com/yaqwsx/PcbDraw/blob/master/doc/pcbdraw.md#usage) output, which will include renders of the front and back sides of any printed circuit board layout files (.kicad_pcb) contained within the project repository.

**Feature Use Case**
This CI job will run automatically as a part of pull requests, releases, etc... and will produce .jpg renders for all printed circuit boards (front and back) contained within a project repository.

**Detailed Design**
- [ ] Add [PcbDraw](https://github.com/yaqwsx/PcbDraw) as a submodule to this project:
```bash
git submodule add ../PcbDraw utilities/PcbDraw
```
- [ ] Add `ci/generate-renders` to project:
  - [ ] Supported options:
      - [ ] `--help`: See other project scripts
      - [ ] `--version`: See other project scripts
   - [ ] `function error()`: See other project scripts
   - [ ] `function abort()`: See other project scripts
   - [ ] `function display_help_text()`: See other project scripts
   - [ ] `function display_version()`: See other project scripts
   - [ ] `function main()`: See other project scripts
   - [ ] `function generate_renders()`:

```bash
local layouts; mapfile -t layouts < <( git -C "$repository" ls-files '*.kicad_pcb' | xargs -r -d '\n' -I '{}' find "$repository/{}" ); readonly layouts
local pcbname;

mkdir -p $repository/production-files/pcb-renders

for layout in "${layouts[@]}"; do
  pcbname=$( basename "$layout" )
    if ! "$repository/utilities/PcbDraw/pcbdraw/pcbdraw.py" "$layout" "production-files/pcb-renders/$pcbname-front.jpg"; then
        abort
    fi  
done

for layout in "${layouts[@]}"; do
    pcbname=$( basename "$layout" )
    if ! "$repository/utilities/PcbDraw/pcbdraw/pcbdraw.py" -b "$layout" "production-files/pcb-renders/$pcbname-back.jpg"; then
        abort
    fi  
done
```

- [ ] Add production files generation (and archiving) CI job to `.github/workflows/ci.yml`:
```yaml
generate-renders:
    name: Generate renders
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
            with:
                submodules: recursive
        - name: Generate renders
            shell: bash
            run: ./ci/generate-renders
        - name: Archive generated renders
            uses: actions/upload-artifact@v2
            with:
                name: renders
                path: renders
                retention-days: 7
```
