### ISSUE TITLE
Add PCB renders generation CI job

### ISSUE THREAD

**Issue by apcountryman** [apcountryman/prototype-kicad-project-ci-cd#34]
Add PCB renders generation CI job. The proposed design was outlined in #33.
- [ ] Add [PcbDraw](https://github.com/yaqwsx/PcbDraw) as a repository submodule:
```bash
git submodule add ../PcbDraw utilities/PcbDraw
```
- [ ] Add PCB renders generation script (`ci/generate-pcb-renders`):
    - [ ] Supported options:
        - [ ] `--help`: See other project scripts
        - [ ] `--version`: See other project scripts
    - [ ] `function error()`: See other project scripts
    - [ ] `function abort()`: See other project scripts
    - [ ] `function display_help_text()`: See other project scripts
    - [ ] `function display_version()`: See other project scripts
    - [ ] `function main()`: See other project scripts
    - [ ] `function generate_pcb_renders()`:
```bash
local -r pcb_renders="$repository/pcb-renders"

if ! mkdir pcb_renders; then
    abort
fi

local    layouts; mapfile -t layouts < <( git -C "$repository" ls-files '*.kicad_pcb' | xargs -r -d '\n' -I '{}' find "$repository/{}" ); readonly layouts
local    layout_name
local -r formats=( "jpg" "png" "svg" )

for layout in "${layouts[@]}"; do
    layout_name=$( basename "$layout" )

    for format in "${formats[@]}"; do
        if ! "$repository/utilities/PcbDraw/pcbdraw/pcbdraw.py" "$layout" "$pcb_renders/$layout_name-front.$format"; then
            abort
        fi

        if ! "$repository/utilities/PcbDraw/pcbdraw/pcbdraw.py" -b "$layout" "$pcb_renders/$layout_name-back.$format"; then
            abort
        fi
    done
done
```
- [ ] Add PCB renders generation (and archiving) CI job to `.github/workflows/ci.yml`:
```yaml
generate-pcb-renders:
    name: Generate PCB renders
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
          with:
              submodules: recursive
        - name: Generate PCB renders
          shell: bash
          run: ./ci/generate-pcb-renders
        - name: Archive generated PCB renders
          uses: actions/upload-artifact@v2
          with:
              name: pcb-renders
              path: pcb-renders
              retention-days: 7
```
